if type -q exa
  alias l='exa -lhF'
  alias lS='exa -1SshF'
  alias la='exa -lAhF'
  alias lart='exa -1cartF'
  alias ldot='exa -ld .*'
  alias ll='exa -l'
  alias lr='exa -tRhF'
  alias lrt='exa -1crtF'
  alias ls='ls --color=tty'
  alias lsa='ls -lah'
  alias lsn='exa -1'
  alias lsr='exa -lARhF'
  alias lt='exa -lthF'
end
