if type -q yay
  alias yaclean='yay -Sc'
  alias yaclr='yay -Scc'
  alias yaconf='yay -Pg'
  alias yain='yay -S'
  alias yains='yay -U'
  alias yainsd='yay -S --asdeps'
  alias yaloc='yay -Qi'
  alias yalocs='yay -Qs'
  alias yalst='yay -Qe'
  alias yamir='yay -Syy'
  alias yaorph='yay -Qtd'
  alias yare='yay -R'
  alias yarem='yay -Rns'
  alias yarep='yay -Si'
  alias yareps='yay -Ss'
  alias yasu='yay -Syu --noconfirm'
  alias yaupd='yay -Sy'
  alias yaupg='yay -Syu'
end
