source aliases/common.nu
source aliases/docker.nu
source aliases/exa.nu
source aliases/gh.nu
source aliases/git.nu
source aliases/pacman.nu
source aliases/pre-commit.nu
source aliases/rsync.nu
source aliases/yay.nu
source aliases/sing.nu
